### PR TITLE
Upgrade project dependencies, fix tests, and fix Travis CI

### PR DESCRIPTION
**Pull request by bruceharrison1984**
A bunch of project level changes to try and make it more manageable. Notable changes are:

- Functional tests that utilize paths now run on Windows machines and are able to pass
- Typings have been moved to the NPM package.json
  - Typings is no longer required to install them
  - Better (and more) typing versions were available in the NPM repo than DT
- fs-promise was removed entirely
  - It was only really used in two places
  - It does not support typescript typings, and would throw compile errors
  - Replaced it with a thin shim that is compatible with typescript
- Travis CI pipeline script was updated, and can successfully build again
- Compile with latest version of Node
- Many packages were woefully out of date.
  - Any that could be updated were updated to the newest compatible version that had typings available
- request-promise was swapped out for Axios
  - This was due to mocking issues with request-promise and nock
  - nock seemed to conflict with an internal library(?) for vscode that had to do with application insights and hijacking the http module

End result is the project now compiles without errors on my Windows PC, as well as on the Linux and MacOS boxes provided by TravisCI.

*Sorry about the pull request thrashing, I'm not used to github just yet*

### CODE REVIEW

**Comment by kidtsunami** [comment]
@bruceharrison1984 thrash away, I'm paying attention and am running late on figuring out some of the issues I've experienced this week. I'm out this weekend, but hoping to give it a solid look Monday.

Thanks for all you're doing. Really appreciate the help with Windows!

**Comment by bruceharrison1984** [comment]
Cool, hope to get this stuff sorted out. 

It looks like all the tests are now passing under Linux, but 4 are failing on OSX.

**Comment by kidtsunami** [comment]
Yeah so @bruceharrison1984 mavensMateClient are the tests I'm wrestling with at the moment. I'm thinking that something in the later versions of VS Code is conflicting with Nock. There appears to be an issue with some kind of Microsoft Analytics library and how Nock hijacks the request.

My plan is to create a clean VS Code extension with really basic request functionality (pinging google.com) with some basic nock tests and to create appropriate tickets with the VS Code Extension repo and the Nock repo.

It's also possible that another request mocking framework works better with VS Code but I haven't found anything conclusive.

**Comment by bruceharrison1984** [comment]
Glad you've already got a handle on this then. I thought I was going mad with red/green lights.

**Comment by kidtsunami** [comment]
Haha yeah, it's not reliably reproducible which is always fun.

**Comment by bruceharrison1984** [comment]
Well I'll probably just disregard any failures of them for the time being. I haven't seen them on my Windows box at all, and the Linux box seems to be happy as well. Two outta three aint bad.

**Comment by bruceharrison1984** [comment]
You make any progress on this? I brought my mac home to kick this around and I cannot reproduce the build error locally on Sierra 10.12.4.

**Comment by bruceharrison1984** [comment]
I swapped out request-promise and the nock testing framework. I replaced them with axios for making requests and moxios for testing. The build seems to be consistently passing on my mac, as well as TravisCI. The tests could probably be re-written a bit more elegantly, but they duplicate the original test functionality.

**Comment by kidtsunami** [comment]
@bruceharrison1984 I did a hard re-install through npm (rm'd the node_modules) and attempted to run the tests and it's super odd, but nothing happens, it just ends. Have you tested this on a Mac?

**Comment by bruceharrison1984** [comment]
I did all of this work on my mac, all tests are passing here.

Not sure why your having any issues, I suppose the only difference is I am using yarn instead of NPM, but that shouldn't really matter.

**Comment by kidtsunami** [comment]
Hey mate, it was some weird module dependency issue. A fresh checkout proved to be the solution.

This lovely pull request is now live with v0.8.0

Thank you so much.
bitmoji

**Comment by bruceharrison1984** [comment]
No worries mate, glad to help out!

**Pull request merged**
