### PR TITLE
Added command - 'Run Apex Test Methods'

### PR DESCRIPTION
**Pull request by NikiforovAll**
Hi, 
I've added command 'Run Apex Test Methods' which is sublime text analogue 'Run Apex Test Methods For This Class'.  I really miss this bits since I switched to vs-code.

### CODE REVIEW

**Comment by kidtsunami** [comment]
Your changes are live in 0.8.0, thank you for contributing!
bitmoji

**Comment by ChuckJonas** [comment]
@NikiforovAll great to have this functionality.  I'm working on an ANTLR typescript npm library that will allow retrieving symbols of classes.  When I get it to a better place, I'll maybe add an improvement to give you dropdown options of the test names, instead of having to type them in

**Comment by NikiforovAll** [comment]
@ChuckJonas It would be great. I also consider another approach, it is possible to download all test methods for specified class via salesforce api, but I haven't found suitable commands in mavensmate server.

**Comment by ChuckJonas** [comment]
Didn't think about that but that might be a better approach (as it wouldn't require adding a dependency on my lexer library).

**Pull request merged**
