### PR TITLE
Allow CSS files to be compiled on save, and make tests run on Windows

### PR DESCRIPTION
**Pull request by squibobblepants**
I've taken the liberty of merging your branch in so you get a clean merge :)

<copied from joferraro/MavensMate>

I noticed that the VSCode plugin for Mavensmate didn't compile CSS files for Aura / Lightning components.

I couldn't run it with F5 straight up as it errored trying to load a non-existent settings file. So I fixed that.

Then I added the css type to the auto-compile types (it still bails if they are found in a resource-bundle, same as javascript).

Then I thought I'd run the tests, and found that they didn't pass on Windows. So I started fixing them. Got most of them done, but the activation tests I couldn't grok. I don't undertand mocha / sinon enough to say whether the activation checks should be triggered, and I don't have an OSX / Linux machine at the moment to test if these tests are broken only in Windows?

Anyway please merge this and pop a release out so that I can carry on using VSCode and not have to go over to Atom or something!

### CODE REVIEW

**Comment by kidtsunami** [comment]
Hey @squibobblepants sorry about the delay, still working out some kinks from updating to ^1.0.0...

https://github.com/Microsoft/vscode-extension-vscode/issues/61

Right now tracking down an issue where nock is failing to stub requests properly (or something else is exceptioning out during that process). Should have something wednesday.

**Comment by squibobblepants** [comment]
Hey @kidtsunami no worries! I saw that error in the tests and thought I'd try to fix it too. It seemed to involve upgrading the typescript version though which introduced a load of compilation errors. I'm completely new to Typescript (creating this pull request is the first time I'd heard of it) so I backed slowly away as unfortunately didn't have the time available to learn it properly!

**Comment by bruceharrison1984** [comment]
I just realized I pushed the same fix you did for fixing paths on the tests for Windows. Great minds think alike 😆 I'll have to check these a bit closer next time

**Comment by kidtsunami** [comment]
@squibobblepants hey mate, sorry for the major delay. I just merged a big PR from @bruceharrison1984 and it looks like there is some overlap with yours. Mind re-doing this PR against the latest master and I'll get it in this week.

**Pull request closed without merging**
