### PR TITLE
"compile all tabs" command

### PR DESCRIPTION
**Pull request by ChuckJonas**
Added command to compile all open tabs.

joeferraro/MavensMate#849

### CODE REVIEW

**Comment by ChuckJonas** [comment]
@kidtsunami any thoughts around this one?  This is pretty much the only reason I ever have to switch back to sublime (when refactoring multiple dependent classes).

**Comment by kidtsunami** [comment]
@ChuckJonas yeah, just was curious why you had the workaround "getOpenEditors" vs just using [visibleTextEditors](https://code.visualstudio.com/docs/extensionAPI/vscode-api#1090)

On top of that, we're upgrading the extension to use TS 2.0 and the latest VSCode version (otherwise it was failing tests and I was not confident in pushing any latest projects).

**Comment by ChuckJonas** [comment]
@kidtsunami That's what I thought at first but `visibleTextEditors` doesn't return all the open editors.  Instead it just returns the editor that is currently being shown to the user (multiple if you have split panels; also includes the output consoles).

You can read more about it in my [feature request](https://github.com/Microsoft/vscode/issues/15178) (maybe upvote it as well).

It's definitely a hack but the only way to implement it for the time being.

**Comment by kidtsunami** [comment]
Thanks @ChuckJonas!! Upvoted and when I sort out the latest update to the extension, I'll merge this in!

**Comment by kidtsunami** [comment]
This is live with v0.9.0

**Pull request merged**
