### PR TITLE
Fix ctr a issue

### PR DESCRIPTION
**Pull request by kidtsunami**

### CODE REVIEW

**Comment by ChuckJonas** [comment]
are we bringing mm back!?  lol, I'm still freaking using it (my mm app build is a bit ahead of where it left off).  The official salesforce extension is still quite a ways from catching up to mm

**Comment by kidtsunami** [comment]
@ChuckJonas haha, I don't see a future for mm because while the salesforce extension has a ways to go before it usurps mm, it's definitely going to happen.

At the moment, I'm fixing show-stopping bugs and nothing else.

That doesn't mean you have to stop though. Have at it!

**Comment by kidtsunami** [comment]
I also love how my bleary eyed use of the vsce publish command is captured here for everyone to see. Patch Patch Minor Patch Patch

**Comment by ChuckJonas** [comment]
The only improvement I've really considered making is updating the server to be able to use SFDX creds for login.  Wish I had done it when sfdx first came out, because at this point it probably isn't worth the effort anymore.

**Pull request merged**
